[custom]

enable_rule_generator=true
overwrite_original_rules=true


; ==========================================================
; Chrome Google 翻译（最高优先级）
; ==========================================================

ruleset=🌐 Google翻译,[]DOMAIN-SUFFIX,translate.google.com
ruleset=🌐 Google翻译,[]DOMAIN-SUFFIX,translate.googleapis.com
ruleset=🌐 Google翻译,[]DOMAIN-SUFFIX,translate-pa.googleapis.com
ruleset=🌐 Google翻译,[]DOMAIN-SUFFIX,translate.googleusercontent.com
ruleset=🌐 Google翻译,[]DOMAIN-SUFFIX,chrometranslate.googleapis.com

ruleset=🌐 Google翻译,[]DOMAIN-SUFFIX,clients1.google.com
ruleset=🌐 Google翻译,[]DOMAIN-SUFFIX,clients2.google.com
ruleset=🌐 Google翻译,[]DOMAIN-SUFFIX,clients3.google.com
ruleset=🌐 Google翻译,[]DOMAIN-SUFFIX,clients4.google.com
ruleset=🌐 Google翻译,[]DOMAIN-SUFFIX,clients5.google.com
ruleset=🌐 Google翻译,[]DOMAIN-SUFFIX,clients6.google.com

ruleset=🌐 Google翻译,[]DOMAIN-SUFFIX,gstatic.com
ruleset=🌐 Google翻译,[]DOMAIN-SUFFIX,googleapis.com
ruleset=🌐 Google翻译,[]DOMAIN-SUFFIX,googleusercontent.com

ruleset=🌐 Google翻译,[]DOMAIN-SUFFIX,ogs.google.com
ruleset=🌐 Google翻译,[]DOMAIN-SUFFIX,optimizationguide-pa.googleapis.com
ruleset=🌐 Google翻译,[]DOMAIN-SUFFIX,mtalk.google.com

ruleset=🌐 Google翻译,[]DOMAIN-KEYWORD,translate


; ==========================================================
; Bigo
; ==========================================================

ruleset=🎥 Bigo,[]DOMAIN-KEYWORD,bigo
ruleset=🎥 Bigo,[]DOMAIN-SUFFIX,bigo.tv
ruleset=🎥 Bigo,[]DOMAIN-SUFFIX,bigo.com
ruleset=🎥 Bigo,[]DOMAIN-SUFFIX,bigoapi.com


; ==========================================================
; DNS
; ==========================================================

ruleset=DIRECT,[]DST-PORT,53


; ==========================================================
; 内网
; ==========================================================

ruleset=DIRECT,[]IP-CIDR,192.168.0.0/16,no-resolve
ruleset=DIRECT,[]IP-CIDR,10.0.0.0/8,no-resolve
ruleset=DIRECT,[]IP-CIDR,172.16.0.0/12,no-resolve


; ==========================================================
; 本地服务
; ==========================================================

rule=DOMAIN-SUFFIX,tailscale.com,DIRECT
rule=DOMAIN-SUFFIX,ts.net,DIRECT
rule=DOMAIN-SUFFIX,log.tailscale.io,DIRECT
rule=DOMAIN-SUFFIX,log.tailscale.com,DIRECT

rule=DOMAIN-SUFFIX,amaigg.eu,DIRECT

rule=DOMAIN-SUFFIX,hp.com,DIRECT
rule=DOMAIN-SUFFIX,hpe.com,DIRECT
rule=DOMAIN-SUFFIX,hpconnected.com,DIRECT
rule=DOMAIN-SUFFIX,hpsupport.com,DIRECT

rule=DOMAIN-SUFFIX,opensubtitles.com,DIRECT


; ==========================================================
; Private
; ==========================================================

ruleset=DIRECT,[]GEOSITE,private
ruleset=DIRECT,[]GEOIP,private,no-resolve


; ==========================================================
; Adobe
; ==========================================================

ruleset=🟥 Adobe,[]GEOSITE,adobe


; ==========================================================
; AI
; ==========================================================

ruleset=🤖 ChatGPT,[]GEOSITE,openai
ruleset=🧠 AI,[]GEOSITE,category-ai-!cn


; ==========================================================
; Google其它服务
; ==========================================================

ruleset=🔎 Google,[]GEOSITE,google


; ==========================================================
; 国内
; ==========================================================

ruleset=DIRECT,[]GEOSITE,cn
ruleset=DIRECT,[]GEOIP,cn,no-resolve; ==========================================================
; 国内服务
; ==========================================================

ruleset=DIRECT,[]GEOSITE,google-cn
ruleset=DIRECT,[]GEOSITE,category-games@cn
ruleset=DIRECT,[]GEOSITE,category-game-platforms-download
ruleset=DIRECT,[]GEOSITE,category-public-tracker


; ==========================================================
; 常用国外服务
; ==========================================================

ruleset=🍎 Apple,[]GEOSITE,apple

ruleset=🎬 YouTube,[]GEOSITE,youtube

ruleset=🎥 Netflix,[]GEOSITE,netflix

ruleset=📨 Telegram,[]GEOSITE,telegram

ruleset=📦 Notion,[]GEOSITE,notion

ruleset=🎵 TikTok,[]GEOSITE,tiktok

ruleset=📸 Instagram,[]GEOSITE,instagram

ruleset=🐦 X,[]GEOSITE,twitter

ruleset=🧑‍💻 GitHub,[]GEOSITE,github

ruleset=🎮 Steam,[]GEOSITE,steam


; ==========================================================
; 金融
; ==========================================================

ruleset=🟦 OKX,[]GEOSITE,okx

ruleset=🟨 Binance,[]GEOSITE,binance

ruleset=🟪 Bybit,[]GEOSITE,bybit


; ==========================================================
; 通讯
; ==========================================================

ruleset=📞 即时通讯,[]GEOSITE,category-communication

ruleset=💬 社交媒体,[]GEOSITE,category-social-media-!cn


; ==========================================================
; Cloudflare
; ==========================================================

ruleset=☁️ cloudflare,[]GEOSITE,cloudflare


; ==========================================================
; Microsoft
; ==========================================================

ruleset=🪟 Microsoft,[]GEOSITE,microsoft


; ==========================================================
; GFW
; ==========================================================

ruleset=🚀 手动选择,[]GEOSITE,gfw


; ==========================================================
; Aethersailor规则
; ==========================================================

ruleset=DIRECT,clash-domain:https://cdn.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct_Domain.yaml,28800

ruleset=DIRECT,clash-classic:https://cdn.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct_Classical_IP.yaml,28800


ruleset=🚀 手动选择,clash-domain:https://cdn.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Proxy_Domain.yaml,28800

ruleset=🚀 手动选择,clash-classic:https://cdn.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Proxy_Classical_IP.yaml,28800


; ==========================================================
; 最终规则
; ==========================================================

ruleset=🐟 漏网之鱼,[]FINAL



; ==========================================================
; 基础策略组
; ==========================================================


custom_proxy_group=🌐 Default`select`[]♻️ 自动选择`[]☁️ CF 优选`[]🇯🇵 JP`[]🇸🇬 SG`[]🇺🇸 US`[]🇭🇰 HK`[]🇹🇼 TW`[]🧭 手动选择`[]DIRECT


custom_proxy_group=🚀 手动选择`select`[]♻️ 自动选择`[]☁️ CF 优选`[]🇯🇵 JP`[]🇸🇬 SG`[]🇺🇸 US`[]🇭🇰 HK`[]🇹🇼 TW`[]🧭 手动选择`[]DIRECT


custom_proxy_group=🐟 漏网之鱼`select`[]🌐 Default`[]🚀 手动选择`[]♻️ 自动选择`[]DIRECT


custom_proxy_group=🐟 遵循规则`select`[]🐟 漏网之鱼



; ==========================================================
; Google翻译专用
; ==========================================================

custom_proxy_group=🌐 Google翻译`select`[]🇯🇵 JP`[]🇸🇬 SG`[]🇺🇸 US`[]🌐 Default`[]♻️ 自动选择`[]🧭 手动选择



; ==========================================================
; Bigo
; ==========================================================

custom_proxy_group=🎥 Bigo`select`[]🇯🇵 JP`[]🌐 Default`[]🇸🇬 SG`[]🇭🇰 HK`[]🇹🇼 TW`[]♻️ 自动选择`[]🧭 手动选择



; ==========================================================
; Google
; ==========================================================

custom_proxy_group=🔎 Google`select`[]🇯🇵 JP`[]🇸🇬 SG`[]🇺🇸 US`[]🌐 Default`[]♻️ 自动选择`[]🧭 手动选择



; ==========================================================
; ChatGPT
; ==========================================================

custom_proxy_group=🤖 ChatGPT`select`[]🇯🇵 JP`[]🇸🇬 SG`[]🇺🇸 US`[]🌐 Default`[]♻️ 自动选择`[]🧭 手动选择


custom_proxy_group=🧠 AI`select`[]🇯🇵 JP`[]🇸🇬 SG`[]🇺🇸 US`[]🌐 Default`[]♻️ 自动选择`[]🧭 手动选择`[]DIRECT
; ==========================================================
; Apple
; ==========================================================

custom_proxy_group=🍎 Apple`select`[]DIRECT`[]🇯🇵 JP`[]🌐 Default`[]♻️ 自动选择



; ==========================================================
; YouTube
; ==========================================================

custom_proxy_group=🎬 YouTube`select`[]🇯🇵 JP`[]🇸🇬 SG`[]🇺🇸 US`[]🌐 Default`[]♻️ 自动选择`[]🧭 手动选择



; ==========================================================
; Netflix
; ==========================================================

custom_proxy_group=🎥 Netflix`select`[]🇯🇵 JP`[]🇺🇸 US`[]🇸🇬 SG`[]🌐 Default`[]♻️ 自动选择`[]🧭 手动选择



; ==========================================================
; Telegram
; ==========================================================

custom_proxy_group=📨 Telegram`select`[]🇯🇵 JP`[]🇸🇬 SG`[]🇭🇰 HK`[]🌐 Default`[]♻️ 自动选择`[]DIRECT



; ==========================================================
; Notion
; ==========================================================

custom_proxy_group=📦 Notion`select`[]🇯🇵 JP`[]🇸🇬 SG`[]🇺🇸 US`[]🌐 Default`[]♻️ 自动选择`[]DIRECT



; ==========================================================
; TikTok
; ==========================================================

custom_proxy_group=🎵 TikTok`select`[]🇯🇵 JP`[]🇸🇬 SG`[]🇺🇸 US`[]🌐 Default`[]♻️ 自动选择



; ==========================================================
; Instagram
; ==========================================================

custom_proxy_group=📸 Instagram`select`[]🇯🇵 JP`[]🇸🇬 SG`[]🇺🇸 US`[]🌐 Default`[]♻️ 自动选择



; ==========================================================
; X
; ==========================================================

custom_proxy_group=🐦 X`select`[]🇯🇵 JP`[]🇺🇸 US`[]🇸🇬 SG`[]🌐 Default`[]♻️ 自动选择



; ==========================================================
; GitHub
; ==========================================================

custom_proxy_group=🧑‍💻 GitHub`select`[]🇯🇵 JP`[]☁️ CF 优选`[]🌐 Default`[]♻️ 自动选择



; ==========================================================
; Steam
; ==========================================================

custom_proxy_group=🎮 Steam`select`[]DIRECT`[]🇯🇵 JP`[]🌐 Default`[]♻️ 自动选择



; ==========================================================
; 金融
; ==========================================================

custom_proxy_group=🟦 OKX`select`[]🇯🇵 JP`[]🇸🇬 SG`[]🌐 Default`[]DIRECT

custom_proxy_group=🟨 Binance`select`[]🇯🇵 JP`[]🇸🇬 SG`[]🌐 Default`[]DIRECT

custom_proxy_group=🟪 Bybit`select`[]🇯🇵 JP`[]🇸🇬 SG`[]🌐 Default`[]DIRECT



; ==========================================================
; 通讯
; ==========================================================

custom_proxy_group=📞 即时通讯`select`[]🌐 Default`[]🇯🇵 JP`[]🇸🇬 SG`[]🇭🇰 HK`[]♻️ 自动选择`[]DIRECT


custom_proxy_group=💬 社交媒体`select`[]🌐 Default`[]🇯🇵 JP`[]🇸🇬 SG`[]🇺🇸 US`[]♻️ 自动选择



; ==========================================================
; Adobe
; ==========================================================

custom_proxy_group=🟥 Adobe`select`[]🌐 Default`[]🇯🇵 JP`[]🇺🇸 US`[]DIRECT`[]REJECT



; ==========================================================
; Cloudflare
; ==========================================================

custom_proxy_group=☁️ cloudflare`select`[]DIRECT`[]☁️ CF 优选`[]🇯🇵 JP`[]🌐 Default`[]♻️ 自动选择



; ==========================================================
; Microsoft
; ==========================================================

custom_proxy_group=🪟 Microsoft`select`[]DIRECT`[]🇯🇵 JP`[]🌐 Default`[]♻️ 自动选择



; ==========================================================
; 非标端口
; ==========================================================

custom_proxy_group=🔀 非标端口`select`[]🎥 Bigo`[]🌐 Default`[]DIRECT`[]🐟 遵循规则



; ==========================================================
; 自动测速
; ==========================================================

custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50



; ==========================================================
; CF优选
; ==========================================================

custom_proxy_group=☁️ CF 优选`url-test`(?i)CF|Cloudflare|优选|CDN|Anycast`http://www.gstatic.com/generate_204`300,,50



; ==========================================================
; 日本节点
; ==========================================================

custom_proxy_group=🇯🇵 JP`url-test`(?i)JP|日本|东京|大阪|Tokyo|Osaka|Japan`http://www.gstatic.com/generate_204`300,,50



; ==========================================================
; 新加坡节点
; ==========================================================

custom_proxy_group=🇸🇬 SG`url-test`(?i)SG|新加坡|Singapore`http://www.gstatic.com/generate_204`300,,50



; ==========================================================
; 美国节点
; ==========================================================

custom_proxy_group=🇺🇸 US`url-test`(?i)US|美国|Los Angeles|United States`http://www.gstatic.com/generate_204`300,,50



; ==========================================================
; 香港节点
; ==========================================================

custom_proxy_group=🇭🇰 HK`url-test`(?i)HK|香港|Hong Kong`http://www.gstatic.com/generate_204`300,,50



; ==========================================================
; 台湾节点
; ==========================================================

custom_proxy_group=🇹🇼 TW`url-test`(?i)TW|台湾|Taiwan`http://www.gstatic.com/generate_204`300,,50



; ==========================================================
; 冷门节点
; ==========================================================

custom_proxy_group=🧊 冷门节点`select`(?i)^(?!.*(HK|香港|JP|日本|SG|新加坡|US|美国|TW|台湾|CF|Cloudflare|流量|套餐|到期|Expire|Traffic)).*

